# fly.toml file generated for mwservice on 2023-04-05T10:14:52+02:00

app = "mwservice"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "waw"
processes = []

[env]
  ASPNETCORE_URLS="http://+:8080"

[build]
  image = "krtfpls/wmservice"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
